export default {
  locale: "fr",
  labels: {
    nav: {
      brand: "LE GOUVERNEUR",
      home: "Accueil",
      services: "Services",
      catalogue: "Catalogue",
      orders: "Commander",
      dashboard: "Espace client",
      transactions: "Transactions",
      documents: "Documents",
      payments: "Paiements",
      notifications: "Notifications",
      profile: "Profil",
      qr: "QR code",
      contact: "Contact",
      login: "Connexion",
      register: "Inscription",
      logout: "Deconnexion",
    },
    cta: {
      discover: "Decouvrir les services",
      startOrder: "Voir",
      openDashboard: "Ouvrir le dashboard",
      viewDetails: "Voir la plateforme",
      payNow: "Payer maintenant",
      trackOrder: "Suivre la demande",
      createAccount: "Creer un compte unique",
    },
    home: {
      eyebrow: "Plateforme omni-services",
      title: "Un seul site, tous les services.",
      lead: "Decouvrez, commandez, payez, suivez et telechargez tous vos dossiers depuis un compte unique.",
      reasonTitle: "Pourquoi LE GOUVERNEUR",
      reasonLead: "Une plateforme serieuse, fluide et mobile pour centraliser les services essentiels des particuliers et des entreprises.",
      processTitle: "Un parcours simple en 4 etapes",
      trustTitle: "Une operation fiable, multi-devises et mobile",
    },
    auth: {
      loginTitle: "Connectez-vous a votre espace client",
      registerTitle: "Creez votre compte omni-services",
      forgotTitle: "Recuperer votre acces",
    },
    orders: {
      createTitle: "Creer une demande",
      paymentTitle: "Payer et confirmer",
      trackingTitle: "Suivi de dossier",
      successTitle: "Commande confirmee",
    },
    services: {
      immobilier: {
        title: "Le Gouverneur Immobilier",
        short: "Vente, location, gestion, investissement et developpement de biens.",
        description: "Confiez vos projets immobiliers a une structure capable de vendre, louer, gerer, valoriser et accompagner vos decisions d'investissement avec une presentation plus elegante et un suivi plus rassurant.",
      },
      importExport: {
        title: "Import - Export",
        short: "Sourcing, transit et suivi douanier.",
        description: "Centralisez vos operations commerciales avec un suivi clair des marchandises, formalites et livraisons.",
      },
      administratif: {
        title: "Services administratifs",
        short: "Demarches, dossiers et legalisation.",
        description: "Confiez la constitution et le suivi de vos dossiers a un point de contact unique.",
      },
      tech: {
        title: "Informatique & electricite",
        short: "Installation, maintenance et depannage.",
        description: "Une reponse rapide pour vos besoins techniques, du diagnostic a l'intervention.",
      },
      transfer: {
        title: "Transfert d'argent",
        short: "Envoyer, recevoir et verifier.",
        description: "Gerez vos transferts avec suivi, confirmation et historique centralise.",
      },
      microfinance: {
        title: "Microfinance / Credit",
        short: "Simulation, demande et echeancier.",
        description: "Suivez vos besoins de financement avec une experience structuree et transparente.",
      },
      documents: {
        title: "Generation de documents (PDF)",
        short: "Formulaires, attestations et exports.",
        description: "Generez vos documents telechargeables avec une logique simple, rapide et archivee.",
      },
      logistics: {
        title: "Logistique & livraison",
        short: "Transport, suivi et preuve de livraison.",
        description: "Planifiez, payez et suivez vos expeditions depuis la meme interface.",
      },
    },
    dashboard: {
      title: "Votre compte unique",
      subtitle: "Tout votre suivi client dans un seul espace.",
      quickActions: "Actions rapides",
      recentDocuments: "Documents recents",
      recentNotifications: "Notifications",
    },
    forms: {
      fullName: "Nom complet",
      email: "Adresse email",
      phone: "Telephone",
      details: "Details",
      notes: "Notes",
      amount: "Montant",
      currency: "Devise",
      submit: "Valider",
      service: "Service",
    },
    status: {
      pending: "Recu",
      in_progress: "En cours",
      paid: "Paye",
      delivered: "Livre",
      cancelled: "Annule",
    },
    currencies: {
      usd: "Dollar americain",
      htg: "Gourde haitienne",
      dop: "Peso dominicain",
    },
  },
};
