export const PRODUCT_CATEGORIES = {
  all: "Tous",
  communication: "Communication",
  transport: "Transport",
  domestic: "Domestique",
  medical: "Médical",
  industrial: "Industriel",
};

export const PRODUCT_CATALOG = [
  {
    id: "iphone",
    name: "iPhone (smartphones)",
    category: "communication",
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80",
    imageAlt: "iPhone sur une table",
    description: "La gamme de smartphones emblématique d'Apple.",
  },
  {
    id: "macbook",
    name: "MacBook (ordinateurs)",
    category: "communication",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    imageAlt: "MacBook ouvert",
    description: "Ordinateurs portables puissants et design par Apple.",
  },
  {
    id: "tablets",
    name: "Tablettes",
    category: "communication",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb16c2866?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Tablette avec un stylet",
    description: "Appareils mobiles polyvalents à grand écran.",
  },
  {
    id: "routers",
    name: "Routeurs Internet",
    category: "communication",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Routeur WiFi blanc",
    description: "Connectez votre domicile ou bureau à Internet.",
  },
  {
    id: "headphones",
    name: "Casques et écouteurs Bluetooth",
    category: "communication",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Casque audio sur fond coloré",
    description: "Écoutez votre musique en toute liberté, sans fil.",
  },
  {
    id: "tesla",
    name: "Tesla Model 3 (voiture électrique)",
    category: "transport",
    image: "https://images.unsplash.com/photo-1560958089-b828c1619374?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Tesla Model 3 blanche",
    description: "Voiture électrique alliant performance et technologie.",
  },
  {
    id: "airplanes",
    name: "Avions",
    category: "transport",
    image: "https://images.unsplash.com/photo-1544091499-193a7898f03b?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Avion en vol",
    description: "Transport aérien pour passagers et marchandises.",
  },
  {
    id: "trains",
    name: "Trains rapides",
    category: "transport",
    image: "https://images.unsplash.com/photo-1506012611-350726b36b3f?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Train à grande vitesse sur un pont",
    description: "Voyagez rapidement et confortablement entre les villes.",
  },
  {
    id: "scooters",
    name: "Trottinettes électriques",
    category: "transport",
    image: "https://images.unsplash.com/photo-1593074281292-693a5a1a68a4?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Trottinette électrique garée",
    description: "Solution de mobilité urbaine, pratique et écologique.",
  },
  {
    id: "drones",
    name: "Drones",
    category: "transport",
    image: "https://images.unsplash.com/photo-1507582020474-0a447a4b5264?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Drone en vol",
    description: "Appareils volants sans pilote pour la prise de vue ou la livraison.",
  },
  {
    id: "smart-tv",
    name: "Télévisions intelligentes (Smart TV)",
    category: "domestic",
    image: "https://images.unsplash.com/photo-1593784944633-c8a0f024435d?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Télévision intelligente dans un salon",
    description: "Accédez à un monde de contenu en ligne depuis votre TV.",
  },
  {
    id: "fridge",
    name: "Réfrigérateurs modernes",
    category: "domestic",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Réfrigérateur moderne ouvert",
    description: "Conservez vos aliments de manière optimale et connectée.",
  },
  {
    id: "vacuum-robot",
    name: "Robots aspirateurs",
    category: "domestic",
    image: "https://images.unsplash.com/photo-1620912189835-3278a2365099?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Robot aspirateur sur un sol en bois",
    description: "Le nettoyage de vos sols devient entièrement autonome.",
  },
  {
    id: "ac",
    name: "Climatiseurs",
    category: "domestic",
    image: "https://images.unsplash.com/photo-1566056342993-84a6137a629b?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Unité de climatisation murale",
    description: "Contrôlez la température de votre intérieur avec précision.",
  },
  {
    id: "washing-machine",
    name: "Machines à laver",
    category: "domestic",
    image: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Machine à laver moderne",
    description: "Un linge impeccable avec des programmes intelligents.",
  },
  {
    id: "scanner",
    name: "Appareils de scanner",
    category: "medical",
    image: "https://images.unsplash.com/photo-1611695434398-4f4b33860a52?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Appareil de scanner IRM",
    description: "Technologie d'imagerie médicale pour des diagnostics précis.",
  },
  {
    id: "xray",
    name: "Machines de radiographie",
    category: "medical",
    image: "https://images.unsplash.com/photo-1581092448348-513758453b94?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Équipement de radiographie",
    description: "Outils de diagnostic essentiels basés sur les rayons X.",
  },
  {
    id: "apple-watch",
    name: "Montres connectées (Apple Watch)",
    category: "medical",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Apple Watch au poignet",
    description: "Suivez votre activité et votre santé depuis votre poignet.",
  },
  {
    id: "pacemaker",
    name: "Stimulateurs cardiaques",
    category: "medical",
    image: "https://images.unsplash.com/photo-1631894943503-6b8247b3e55c?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Dispositif médical implantable",
    description: "Dispositifs vitaux pour la régulation du rythme cardiaque.",
  },
  {
    id: "auto-machines",
    name: "Machines automatiques",
    category: "industrial",
    image: "https://images.unsplash.com/photo-1611606023243-9badd9b634c6?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Bras robotique sur une chaîne de production",
    description: "Automatisation et optimisation des processus de fabrication.",
  },
  {
    id: "industrial-robots",
    name: "Robots industriels",
    category: "industrial",
    image: "https://images.unsplash.com/photo-1567779833503-a7d3b2d59c43?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Robot industriel dans une usine",
    description: "Flexibilité et précision pour l'automatisation industrielle.",
  },
  {
    id: "solar-panels",
    name: "Panneaux solaires",
    category: "industrial",
    image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9c?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Champ de panneaux solaires",
    description: "Source d'énergie propre et renouvelable pour l'industrie.",
  },
  {
    id: "storage-batteries",
    name: "Batteries de stockage d’énergie",
    category: "industrial",
    image: "https://images.unsplash.com/photo-1552056723-6a5b39a7b4a3?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Système de stockage d'énergie par batterie",
    description: "Stockage de l'énergie pour une distribution stable et fiable.",
  },
];