export const PAGE_DEFINITIONS = {
  home: { key: "home", layout: "public", requiresAuth: false, pageClass: "home" },
  services: { key: "services", layout: "public", requiresAuth: false, pageClass: "services" },
  serviceDetail: { key: "serviceDetail", layout: "public", requiresAuth: false, pageClass: "serviceDetail" },
  orderCreate: { key: "orderCreate", layout: "public", requiresAuth: false, pageClass: "orderCreate" },
  orderPayment: { key: "orderPayment", layout: "public", requiresAuth: false, pageClass: "orderPayment" },
  orderTracking: { key: "orderTracking", layout: "public", requiresAuth: false, pageClass: "orderTracking" },
  orderSuccess: { key: "orderSuccess", layout: "public", requiresAuth: false, pageClass: "orderSuccess" },
  login: { key: "login", layout: "public", requiresAuth: false, pageClass: "login" },
  register: { key: "register", layout: "public", requiresAuth: false, pageClass: "register" },
  forgotPassword: { key: "forgotPassword", layout: "public", requiresAuth: false, pageClass: "forgotPassword" },
  dashboardHome: { key: "dashboardHome", layout: "dashboard", requiresAuth: true, pageClass: "dashboardHome" },
  dashboardTransactions: { key: "dashboardTransactions", layout: "dashboard", requiresAuth: true, pageClass: "dashboardTransactions" },
  dashboardDocuments: { key: "dashboardDocuments", layout: "dashboard", requiresAuth: true, pageClass: "dashboardDocuments" },
  dashboardPayments: { key: "dashboardPayments", layout: "dashboard", requiresAuth: true, pageClass: "dashboardPayments" },
  dashboardQr: { key: "dashboardQr", layout: "dashboard", requiresAuth: true, pageClass: "dashboardQr" },
  dashboardNotifications: { key: "dashboardNotifications", layout: "dashboard", requiresAuth: true, pageClass: "dashboardNotifications" },
  dashboardProfile: { key: "dashboardProfile", layout: "dashboard", requiresAuth: true, pageClass: "dashboardProfile" },
};
