export const SERVICE_CATALOG = [
  {
    id: "immobilier",
    slug: "immobilier",
    icon: "fa-building",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Maison moderne avec facade lumineuse",
    categoryKey: "real-estate",
    titleKey: "services.immobilier.title",
    shortKey: "services.immobilier.short",
    descriptionKey: "services.immobilier.description",
    route: "/immobilier.html",
    orderType: "real-estate",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Location", "Vente", "Gestion locative"],
    highlights: ["Mandats fiables", "Visites programmees", "Suivi dossier"],
    process: ["Analyse du besoin", "Selection de biens", "Validation", "Remise des documents"],
    requiredDocs: ["Piece d'identite", "Justificatif de revenus", "Reference ou mandat"],
    pricing: {
      base: 120,
      currency: "USD",
      note: "Commission et frais variables selon la mission.",
    },
    faq: [
      "Pouvez-vous gerer un bien a distance ?",
      "Proposez-vous des biens verifies uniquement ?",
    ],
  },
  {
    id: "import-export",
    slug: "import-export",
    icon: "fa-globe",
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Conteneurs et logistique internationale",
    categoryKey: "trade",
    titleKey: "services.importExport.title",
    shortKey: "services.importExport.short",
    descriptionKey: "services.importExport.description",
    route: "/import-export.html",
    orderType: "trade",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Sourcing", "Transit", "Suivi douanier"],
    highlights: ["Conformite", "Pilotage logistique", "Reporting"],
    process: ["Brief marchandises", "Preparation des pieces", "Transit", "Livraison finale"],
    requiredDocs: ["Facture", "Liste de colisage", "Coordonnees expediteur"],
    pricing: {
      base: 240,
      currency: "USD",
      note: "Tarif selon volume, provenance et formalites.",
    },
    faq: [
      "Le suivi est-il disponible en temps reel ?",
      "Prenez-vous en charge les formalites douanieres ?",
    ],
  },
  {
    id: "administratif",
    slug: "administratif",
    icon: "fa-briefcase",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Equipe en reunion autour de documents administratifs",
    categoryKey: "admin",
    titleKey: "services.administratif.title",
    shortKey: "services.administratif.short",
    descriptionKey: "services.administratif.description",
    route: "/administratif.html",
    orderType: "admin",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Demarches", "Constitution de dossier", "Legalisation"],
    highlights: ["Check-list", "Verification", "Livraison PDF"],
    process: ["Recueil des infos", "Montage du dossier", "Depot", "Restitution"],
    requiredDocs: ["Piece d'identite", "Informations du dossier", "Mandat si necessaire"],
    pricing: {
      base: 45,
      currency: "USD",
      note: "Frais variables selon l'administration concernee.",
    },
    faq: [
      "Pouvez-vous remplir les formulaires pour moi ?",
      "Les documents peuvent-ils etre envoyes en PDF ?",
    ],
  },
  {
    id: "informatique-electricite",
    slug: "informatique-electricite",
    icon: "fa-laptop-code",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Composants techniques et maintenance informatique",
    categoryKey: "tech",
    titleKey: "services.tech.title",
    shortKey: "services.tech.short",
    descriptionKey: "services.tech.description",
    route: "/informatique-electricite.html",
    orderType: "tech",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: false,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Installation", "Maintenance", "Depannage"],
    highlights: ["Interventions planifiees", "Diagnostic", "Support terrain"],
    process: ["Diagnostic", "Devis", "Execution", "Compte-rendu"],
    requiredDocs: ["Adresse du site", "Description de la panne", "Photos si possible"],
    pricing: {
      base: 60,
      currency: "USD",
      note: "Intervention sur devis selon complexite et deplacement.",
    },
    faq: [
      "Couvrez-vous les interventions a domicile ?",
      "Le materiel est-il inclus dans vos devis ?",
    ],
  },
  {
    id: "transfert-argent",
    slug: "transfert-argent",
    icon: "fa-money-bill-transfer",
    image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Paiement digital et transfert d argent",
    categoryKey: "finance",
    titleKey: "services.transfer.title",
    shortKey: "services.transfer.short",
    descriptionKey: "services.transfer.description",
    route: "/transfert-argent.html",
    orderType: "money-transfer",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Envoi", "Reception", "Verification"],
    highlights: ["Suivi reference", "Historique", "Confirmation rapide"],
    process: ["Selection du beneficiaire", "Paiement", "Validation", "Notification"],
    requiredDocs: ["Identite expediteur", "Identite beneficiaire", "Montant"],
    pricing: {
      base: 8,
      currency: "USD",
      note: "Frais calcules selon montant et devise.",
    },
    faq: [
      "Puis-je suivre mon transfert en ligne ?",
      "Les trois devises sont-elles prises en charge ?",
    ],
  },
  {
    id: "microfinance-credit",
    slug: "microfinance-credit",
    icon: "fa-landmark",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Analyse financiere et microcredit",
    categoryKey: "finance",
    titleKey: "services.microfinance.title",
    shortKey: "services.microfinance.short",
    descriptionKey: "services.microfinance.description",
    route: "/microfinance-credit.html",
    orderType: "credit",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Simulation", "Demande", "Echeancier"],
    highlights: ["Evaluation rapide", "Pieces centralisees", "Suivi d'echeances"],
    process: ["Prequalification", "Montage", "Analyse", "Decaissement"],
    requiredDocs: ["Identite", "Preuves de revenus", "Objet du financement"],
    pricing: {
      base: 0,
      currency: "USD",
      note: "Simulation gratuite, conditions selon dossier.",
    },
    faq: [
      "Proposez-vous une simulation avant demande ?",
      "Puis-je suivre mes echeances dans le dashboard ?",
    ],
  },
  {
    id: "generation-documents",
    slug: "generation-documents",
    icon: "fa-file-pdf",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Documents et formulaires sur bureau",
    categoryKey: "documents",
    titleKey: "services.documents.title",
    shortKey: "services.documents.short",
    descriptionKey: "services.documents.description",
    route: "/generation-documents.html",
    orderType: "documents",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Formulaires", "Attestations", "Exports PDF"],
    highlights: ["Templates fiables", "Livraison telechargeable", "Historique centralise"],
    process: ["Selection du document", "Saisie", "Validation", "Telechargement"],
    requiredDocs: ["Informations du document", "Nom complet", "Donnees justificatives"],
    pricing: {
      base: 12,
      currency: "USD",
      note: "Prix par document ou pack selon le volume.",
    },
    faq: [
      "Les PDF sont-ils disponibles dans le dashboard ?",
      "Les formulaires sont-ils pre-remplis ?",
    ],
  },
  {
    id: "logistique-livraison",
    slug: "logistique-livraison",
    icon: "fa-truck-fast",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Entrepot et distribution logistique",
    categoryKey: "logistics",
    titleKey: "services.logistics.title",
    shortKey: "services.logistics.short",
    descriptionKey: "services.logistics.description",
    route: "/logistique-livraison.html",
    orderType: "logistics",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Enlevement", "Distribution", "Suivi"],
    highlights: ["Estimation claire", "Trajets suivis", "Preuve de livraison"],
    process: ["Planification", "Collecte", "Acheminement", "Confirmation"],
    requiredDocs: ["Adresse depart", "Adresse arrivee", "Description du colis"],
    pricing: {
      base: 25,
      currency: "USD",
      note: "Tarif selon distance, urgence et dimensions.",
    },
    faq: [
      "Le suivi de livraison est-il inclus ?",
      "Proposez-vous des livraisons express ?",
    ],
  },
];

export function findServiceBySlug(slug) {
  return SERVICE_CATALOG.find((service) => service.slug === slug) || SERVICE_CATALOG[0];
}
