import { appHref } from "./router-state.js";

export const SERVICE_CATALOG = [
  {
    id: "immobilier",
    slug: "immobilier",
    icon: "fa-building",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Maison moderne avec facade lumineuse",
    categoryKey: "real-estate",
    titleKey: "services.immobilier.title",
    shortKey: "services.immobilier.short",
    descriptionKey: "services.immobilier.description",
    route: appHref("/immobilier.html"),
    orderType: "real-estate",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    heroBadge: "Le Gouverneur Immobilier",
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Vente & achat", "Location", "Gestion immobiliere", "Investissement", "Developpement", "Evaluation"],
    highlights: ["Accompagnement complet", "Presentation premium des biens", "Suivi transparent", "Solutions pour particuliers et investisseurs"],
    process: ["Analyse du besoin", "Selection de biens", "Validation", "Remise des documents"],
    requiredDocs: ["Piece d'identite", "Mandat ou reference du bien", "Coordonnees du proprietaire ou acquereur", "Documents du bien si disponibles"],
    pricing: {
      base: 120,
      currency: "USD",
      note: "Honoraires et commissions adaptes selon le type de mission, la valeur du bien et le niveau d'accompagnement souhaite.",
    },
    faq: [
      "Pouvez-vous accompagner une vente ou une location a distance ?",
      "Proposez-vous des services de gestion et de promotion du bien ?",
    ],
    overviewTitle: "Une offre immobiliere complete, claire et rentable",
    overviewText:
      "Le Gouverneur Immobilier reunit vente, location, gestion, conseil et developpement dans une experience plus serieuse, plus fluide et plus rassurante pour les proprietaires, locataires, acheteurs et investisseurs.",
    offerCards: [
      {
        title: "Vente et achat de proprietes",
        description: "Un accompagnement commercial structure pour vendre plus vite ou trouver le bon bien au bon prix.",
        bullets: ["Maisons, terrains, appartements", "Recherche ciblee pour les clients", "Negociation acheteur-vendeur", "Estimation du prix du bien"],
      },
      {
        title: "Location de biens",
        description: "Une mise en location professionnelle avec diffusion, visites et formalisation des accords.",
        bullets: ["Maisons et appartements", "Locaux commerciaux", "Recherche de locataires", "Contrats de bail"],
      },
      {
        title: "Gestion immobiliere",
        description: "Une gestion continue pour securiser le bien, les revenus et la relation avec les occupants.",
        bullets: ["Collecte des loyers", "Gestion des locataires", "Maintenance et reparations", "Rapports financiers proprietaire"],
      },
      {
        title: "Promotion et marketing immobilier",
        description: "Des annonces mieux presentees pour attirer plus rapidement les bons profils.",
        bullets: ["Publicite des proprietes", "Photos et videos", "Publication en ligne", "Organisation des visites"],
      },
      {
        title: "Conseil et investissement immobilier",
        description: "Une lecture plus strategique du marche pour investir avec plus de visibilite.",
        bullets: ["Analyse du marche", "Conseils aux investisseurs", "Etude de rentabilite", "Achat pour investissement"],
      },
      {
        title: "Developpement immobilier",
        description: "Un appui sur les projets immobiliers depuis le terrain jusqu'a la valorisation finale.",
        bullets: ["Construction de maisons ou immeubles", "Lotissement de terrains", "Projets residentiels", "Projets commerciaux"],
      },
      {
        title: "Evaluation et expertise",
        description: "Des evaluations utiles pour vendre, financer, negocier ou rassurer des partenaires.",
        bullets: ["Valeur du bien", "Expertise technique", "Rapport pour banques", "Rapport pour investisseurs"],
      },
      {
        title: "Services financiers lies a l'immobilier",
        description: "Un accompagnement sur les leviers qui facilitent l'acquisition et la protection du bien.",
        bullets: ["Aide pour pret immobilier", "Conseils en financement", "Assurance habitation", "Orientation sur les services juridiques lies"],
      },
      {
        title: "Services annexes",
        description: "Des prestations complementaires pour renforcer l'attractivite et la mise en valeur du bien.",
        bullets: ["Inspection de maison", "Renovation et reparation", "Amenagement interieur", "Service de demenagement"],
      },
    ],
    expertisePillars: [
      {
        value: "9",
        label: "poles de services immobiliers",
      },
      {
        value: "360",
        label: "accompagnement de la recherche a la gestion",
      },
      {
        value: "3",
        label: "profils cibles: proprietaires, acheteurs, investisseurs",
      },
    ],
    signatureStatement:
      "Pour la marque Le Gouverneur Omni-Services Immobilier, la page met en avant une image plus premium: vente, location, gestion, investissement, construction, renovation et evaluation dans un seul univers coherent.",
  },
  {
    id: "import-export",
    slug: "import-export",
    icon: "fa-globe",
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Conteneurs et logistique internationale",
    categoryKey: "trade",
    titleKey: "services.importExport.title",
    shortKey: "services.importExport.short",
    descriptionKey: "services.importExport.description",
    route: appHref("/import-export.html"),
    orderType: "trade",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Sourcing", "Transit", "Suivi douanier"],
    highlights: ["Conformite", "Pilotage logistique", "Reporting"],
    process: ["Brief marchandises", "Preparation des pieces", "Transit", "Livraison finale"],
    requiredDocs: ["Facture", "Liste de colisage", "Coordonnees expediteur"],
    pricing: {
      base: 240,
      currency: "USD",
      note: "Tarif selon volume, provenance et formalites.",
    },
    faq: [
      "Le suivi est-il disponible en temps reel ?",
      "Prenez-vous en charge les formalites douanieres ?",
    ],
  },
  {
    id: "administratif",
    slug: "administratif",
    icon: "fa-briefcase",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Equipe en reunion autour de documents administratifs",
    categoryKey: "admin",
    titleKey: "services.administratif.title",
    shortKey: "services.administratif.short",
    descriptionKey: "services.administratif.description",
    route: appHref("/administratif.html"),
    orderType: "admin",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Demarches", "Constitution de dossier", "Legalisation"],
    highlights: ["Check-list", "Verification", "Livraison PDF"],
    process: ["Recueil des infos", "Montage du dossier", "Depot", "Restitution"],
    requiredDocs: ["Piece d'identite", "Informations du dossier", "Mandat si necessaire"],
    pricing: {
      base: 45,
      currency: "USD",
      note: "Frais variables selon l'administration concernee.",
    },
    faq: [
      "Pouvez-vous remplir les formulaires pour moi ?",
      "Les documents peuvent-ils etre envoyes en PDF ?",
    ],
  },
  {
    id: "informatique-electricite",
    slug: "informatique-electricite",
    icon: "fa-laptop-code",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Composants techniques et maintenance informatique",
    categoryKey: "tech",
    titleKey: "services.tech.title",
    shortKey: "services.tech.short",
    descriptionKey: "services.tech.description",
    route: appHref("/informatique-electricite.html"),
    orderType: "tech",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: false,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Installation", "Maintenance", "Depannage"],
    highlights: ["Interventions planifiees", "Diagnostic", "Support terrain"],
    process: ["Diagnostic", "Devis", "Execution", "Compte-rendu"],
    requiredDocs: ["Adresse du site", "Description de la panne", "Photos si possible"],
    pricing: {
      base: 60,
      currency: "USD",
      note: "Intervention sur devis selon complexite et deplacement.",
    },
    faq: [
      "Couvrez-vous les interventions a domicile ?",
      "Le materiel est-il inclus dans vos devis ?",
    ],
  },
  {
    id: "transfert-argent",
    slug: "transfert-argent",
    icon: "fa-money-bill-transfer",
    image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Paiement digital et transfert d argent",
    categoryKey: "finance",
    titleKey: "services.transfer.title",
    shortKey: "services.transfer.short",
    descriptionKey: "services.transfer.description",
    route: appHref("/transfert-argent.html"),
    orderType: "money-transfer",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Envoi", "Reception", "Verification"],
    highlights: ["Suivi reference", "Historique", "Confirmation rapide"],
    process: ["Selection du beneficiaire", "Paiement", "Validation", "Notification"],
    requiredDocs: ["Identite expediteur", "Identite beneficiaire", "Montant"],
    pricing: {
      base: 8,
      currency: "USD",
      note: "Frais calcules selon montant et devise.",
    },
    faq: [
      "Puis-je suivre mon transfert en ligne ?",
      "Les trois devises sont-elles prises en charge ?",
    ],
  },
  {
    id: "microfinance-credit",
    slug: "microfinance-credit",
    icon: "fa-landmark",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Analyse financiere et microcredit",
    categoryKey: "finance",
    titleKey: "services.microfinance.title",
    shortKey: "services.microfinance.short",
    descriptionKey: "services.microfinance.description",
    route: appHref("/microfinance-credit.html"),
    orderType: "credit",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Simulation", "Demande", "Echeancier"],
    highlights: ["Evaluation rapide", "Pieces centralisees", "Suivi d'echeances"],
    process: ["Prequalification", "Montage", "Analyse", "Decaissement"],
    requiredDocs: ["Identite", "Preuves de revenus", "Objet du financement"],
    pricing: {
      base: 0,
      currency: "USD",
      note: "Simulation gratuite, conditions selon dossier.",
    },
    faq: [
      "Proposez-vous une simulation avant demande ?",
      "Puis-je suivre mes echeances dans le dashboard ?",
    ],
  },
  {
    id: "generation-documents",
    slug: "generation-documents",
    icon: "fa-file-pdf",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Documents et formulaires sur bureau",
    categoryKey: "documents",
    titleKey: "services.documents.title",
    shortKey: "services.documents.short",
    descriptionKey: "services.documents.description",
    route: appHref("/generation-documents.html"),
    orderType: "documents",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Formulaires", "Attestations", "Exports PDF"],
    highlights: ["Templates fiables", "Livraison telechargeable", "Historique centralise"],
    process: ["Selection du document", "Saisie", "Validation", "Telechargement"],
    requiredDocs: ["Informations du document", "Nom complet", "Donnees justificatives"],
    pricing: {
      base: 12,
      currency: "USD",
      note: "Prix par document ou pack selon le volume.",
    },
    faq: [
      "Les PDF sont-ils disponibles dans le dashboard ?",
      "Les formulaires sont-ils pre-remplis ?",
    ],
  },
  {
    id: "logistique-livraison",
    slug: "logistique-livraison",
    icon: "fa-truck-fast",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Entrepot et distribution logistique",
    categoryKey: "logistics",
    titleKey: "services.logistics.title",
    shortKey: "services.logistics.short",
    descriptionKey: "services.logistics.description",
    route: appHref("/logistique-livraison.html"),
    orderType: "logistics",
    supportsPayment: true,
    supportsTracking: true,
    supportsDocuments: true,
    currencies: ["USD", "HTG", "DOP"],
    subServices: ["Enlevement", "Distribution", "Suivi"],
    highlights: ["Estimation claire", "Trajets suivis", "Preuve de livraison"],
    process: ["Planification", "Collecte", "Acheminement", "Confirmation"],
    requiredDocs: ["Adresse depart", "Adresse arrivee", "Description du colis"],
    pricing: {
      base: 25,
      currency: "USD",
      note: "Tarif selon distance, urgence et dimensions.",
    },
    faq: [
      "Le suivi de livraison est-il inclus ?",
      "Proposez-vous des livraisons express ?",
    ],
  },
];

export function findServiceBySlug(slug) {
  return SERVICE_CATALOG.find((service) => service.slug === slug) || SERVICE_CATALOG[0];
}
